 <LI>Only the <B>&lt;IMG&gt;</B> tag with its <B>SRC</B> pointing to an <B>ashx</B> file is required for graphics</LI>
 <LI>So plain <B>HTML</B> pages can be used to create graphics</LI>
 <LI>Graphics can be altered <B>dynamically</B> without reloading the whole page</LI>
 <LI>Graphics can be created <B>without</B> any aspx pages or codebehind</LI>
 <LI><I>Of course, if necessay the <B>SRC</B> for graphics can be created in aspx pages with codebehind</I></LI>
