
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, and Azure
-- --------------------------------------------------
-- Date Created: 11/22/2012 09:16:54
-- Generated from EDMX file: E:\Capstone\CrimeAwareSite\CrimeAware\App_Code\CrimeData_model.edmx
-- --------------------------------------------------
USE CCSS
GO

CREATE TABLE SCHOOLS (
  SCHOOL_ID INTEGER  NOT NULL   IDENTITY ,
  SCHOOL_NAME VARCHAR(40)  NOT NULL  ,
  CITY VARCHAR(40)  NOT NULL  ,
  STATE CHAR(2)  NOT NULL    ,
  ABBREVIATION VARCHAR(10)  NOT NULL  ,
PRIMARY KEY(SCHOOL_ID));
GO

CREATE TABLE USERS (
  USER_ID INTEGER  NOT NULL   IDENTITY ,
  USER_TYPE CHAR(1)  NOT NULL  ,
  NAME VARCHAR(40)  NOT NULL  ,
  PASSWORD_ENC VARCHAR(40)    ,
  ACTIVE_IND CHAR(1)  NOT NULL  ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER    ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(USER_ID));
GO

CREATE TABLE WEATHER_INFO (
  SCHOOL_ID INTEGER  NOT NULL  ,
  WEATHER_START_DATE DATETIME  NOT NULL    ,
  WEATHER_END_DATE DATETIME  NOT NULL  ,
  TEMPERATURE NUMERIC(3)    ,
  SUNNY_IND CHAR(1)    ,
  RAINY_IND CHAR(1)      ,
PRIMARY KEY(SCHOOL_ID, WEATHER_START_DATE, WEATHER_END_DATE)  ,
  FOREIGN KEY(SCHOOL_ID)
    REFERENCES SCHOOLS(SCHOOL_ID));
GO

CREATE TABLE EVENT_TYPES (
  EVENT_TYPE_ID INTEGER  NOT NULL   IDENTITY ,
  EVENT_TYPE_NAME VARCHAR(40)  NOT NULL  ,
  ACTIVE_IND CHAR(1)  NOT NULL  ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER    ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(EVENT_TYPE_ID)    ,
  FOREIGN KEY(CREATED_BY)
    REFERENCES USERS(USER_ID),
  FOREIGN KEY(MODIFIED_BY)
    REFERENCES USERS(USER_ID));
GO

CREATE TABLE SCHOOL_BUILDINGS (
  SCHOOL_BUILDINGS_ID INTEGER  NOT NULL IDENTITY ,
  SCHOOL_ID INTEGER  NOT NULL  ,
  BUILDING_NAME VARCHAR(40)  NOT NULL  ,
  LAT_START NUMERIC(9,6)  NOT NULL  ,
  LAT_END NUMERIC(9,6)    ,
  LONG_START NUMERIC(9,6)  NOT NULL  ,
  LONG_END NUMERIC(9,6)    ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER   ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(SCHOOL_BUILDINGS_ID)      ,
  FOREIGN KEY(SCHOOL_ID)
    REFERENCES SCHOOLS(SCHOOL_ID),
  FOREIGN KEY(CREATED_BY)
    REFERENCES USERS(USER_ID),
  FOREIGN KEY(MODIFIED_BY)
    REFERENCES USERS(USER_ID));
GO

CREATE TABLE EVENT_DATA (
  EVENT_ID INTEGER  NOT NULL   IDENTITY ,
  EVENT_DATE DATETIME  NOT NULL  ,
  EVENT_END_DATE DATETIME    ,
  LOCATION_LAT NUMERIC(9,6)  NOT NULL  ,
  LOCATION_LONG NUMERIC(9,6)  NOT NULL  ,
  LOCATION_END_LAT NUMERIC(9,6)    ,
  LOCATION_END_LONG NUMERIC(9,6)    ,
  SCHOOL_ID INTEGER    ,
  ARREST_IND CHAR(1)  NOT NULL  ,
  VICITIM_SEX CHAR(1)    ,
  VICTIM_AGE NUMERIC(3)    ,
  VICTIM_STUDENT_IND CHAR(1)    ,
  OFFENDER_SEX CHAR(1)    ,
  OFFENDER_AGE NUMERIC(3)    ,
  OFFENDER_STUDENT_IND CHAR(1)    ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER    ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(EVENT_ID)      ,
  FOREIGN KEY(SCHOOL_ID)
    REFERENCES SCHOOLS(SCHOOL_ID),
  FOREIGN KEY(CREATED_BY)
    REFERENCES USERS(USER_ID),
  FOREIGN KEY(MODIFIED_BY)
    REFERENCES USERS(USER_ID));
GO

CREATE TABLE SCHEDULE (
  SCHEDULE_ID INTEGER  NOT NULL   IDENTITY ,
  SCHOOL_ID INTEGER  NOT NULL  ,
  SCHEDULE_DATE DATE  NOT NULL  ,
  NAME VARCHAR(40)    ,
  HOLIDAY_IND CHAR(1)  NOT NULL  ,
  SCHOOL_INSESSION_IND CHAR(1)  NOT NULL  ,
  EXAM_IND CHAR(1)  NOT NULL  ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER    ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(SCHEDULE_ID)      ,
  FOREIGN KEY(SCHOOL_ID)
    REFERENCES SCHOOLS(SCHOOL_ID),
  FOREIGN KEY(CREATED_BY)
    REFERENCES USERS(USER_ID),
  FOREIGN KEY(MODIFIED_BY)
    REFERENCES USERS(USER_ID));
GO

CREATE TABLE EVENT_DATA_TYPES (
  EVENT_ID INTEGER  NOT NULL   ,
  EVENT_TYPE_ID INTEGER  NOT NULL  ,
  CREATED_BY INTEGER  NOT NULL  ,
  CREATED_DATE DATETIME  NOT NULL  ,
  MODIFIED_BY INTEGER  ,
  MODIFIED_DATE DATETIME      ,
PRIMARY KEY(EVENT_ID, EVENT_TYPE_ID)        ,
  FOREIGN KEY(EVENT_ID)
    REFERENCES EVENT_DATA(EVENT_ID),
  FOREIGN KEY(EVENT_TYPE_ID)
    REFERENCES EVENT_TYPES(EVENT_TYPE_ID),
  FOREIGN KEY(CREATED_BY)
    REFERENCES USERS(USER_ID),
  FOREIGN KEY(MODIFIED_BY)
    REFERENCES USERS(USER_ID));
GO
